# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    web_dir: '/uploads'
    root_path: '%kernel.project_dir%'
    secured_dir: '/secured_files'
    private_spaces_dir: '/private_spaces_files'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Akyos\FileManagerBundle\:
        resource: './../../*'
        tags: [ 'controller.service_arguments' ]
        public: true

    Akyos\FileManagerBundle\Annotations\PathAnnotation:
        arguments:
            $values: [ ]
